import React, { useState } from "react";
import SidebarComponent from "../Components/Sidebar"

const ReportPage = () => {
  const reports = [
    {
      id: 1,
      title: "User Activity Report",
      date: "2024-11-01",
      generatedBy: "Admin User",
      status: "Completed",
      actions: "View",
    },
    {
      id: 2,
      title: "Sales Report",
      date: "2024-11-05",
      generatedBy: "Super Admin",
      status: "Completed",
      actions: "View",
    },
    {
      id: 3,
      title: "Ticket Sales Report",
      date: "2024-11-10",
      generatedBy: "Admin User",
      status: "Pending",
      actions: "View",
    },
    {
      id: 4,
      title: "Revenue Report",
      date: "2024-11-12",
      generatedBy: "Admin User",
      status: "Completed",
      actions: "View",
    },
  ];


  const [statusFilter, setStatusFilter] = useState("All");


  const filteredReports =
    statusFilter === "All"
      ? reports
      : reports.filter((report) => report.status === statusFilter);

  return (
    <>
    <SidebarComponent/>
    <div className="ml-52 xl:ml-60 max-sm:ml-0 flex-1 ">
    <div className="p-6 bg-gray-900 min-h-screen">
      <h1 className="text-2xl font-bold text-gray-200 mb-6">Reports</h1>

      <div className="mb-6 flex justify-between items-center">
        <div>
          <h2 className="text-lg font-semibold text-gray-300">Filter by Status</h2>
          <select
            className="mt-2 p-2 border border-gray-700 rounded bg-gray-800 text-gray-300"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="All">All</option>
            <option value="Completed">Completed</option>
            <option value="Pending">Pending</option>
          </select>
        </div>


        <button className="bg-orange-400 text-white py-2 px-4 rounded hover:bg-orange-500">
          view All Reports
        </button>
      </div>


      <div className="overflow-x-auto bg-gray-800 shadow rounded-lg">
        <table className="w-full table-auto">
          <thead className="bg-gray-800">
            <tr>
              <th className="py-3 px-4 text-left text-gray-300">Report Title</th>
              <th className="py-3 px-4 text-left text-gray-300">Date</th>
              <th className="py-3 px-4 text-left text-gray-300">Generated By</th>
              <th className="py-3 px-4 text-left text-gray-300">Status</th>
              <th className="py-3 px-4 text-left text-gray-300">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.map((report) => (
              <tr key={report.id} className="border-b">
                <td className="py-3 px-4 text-gray-300">{report.title}</td>
                <td className="py-3 px-4 text-gray-300">{report.date}</td>
                <td className="py-3 px-4 text-gray-300">{report.generatedBy}</td>
                <td
                  className={`py-3 px-4 text-gray-300 ${
                    report.status === "Completed" ? "text-green-500" : "text-orange-400"
                  }`}
                >
                  {report.status}
                </td>
                <td className="py-3 px-4">
                  <button
                    className={`py-2 px-4 rounded ${
                      report.status === "Completed"
                        ? "bg-green-500 text-white hover:bg-green-600"
                        : "bg-orange-400 px-5 text-white hover:bg-orange-500"
                    }`}
                  >
                    {report.actions}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
    </div>
    </>
  );
};

export default ReportPage;
