import React, { useState } from "react";

const ReportPage = () => {
  const reports = [
    {
      id: 1,
      title: "User Activity Report",
      date: "2024-11-01",
      generatedBy: "Admin User",
      status: "Completed",
      actions: "Download",
    },
    {
      id: 2,
      title: "Sales Report",
      date: "2024-11-05",
      generatedBy: "Super Admin",
      status: "Completed",
      actions: "Download",
    },
    {
      id: 3,
      title: "Ticket Sales Report",
      date: "2024-11-10",
      generatedBy: "Admin User",
      status: "Pending",
      actions: "Generate",
    },
    {
      id: 4,
      title: "Revenue Report",
      date: "2024-11-12",
      generatedBy: "Admin User",
      status: "Completed",
      actions: "Download",
    },
  ];


  const [statusFilter, setStatusFilter] = useState("All");


  const filteredReports =
    statusFilter === "All"
      ? reports
      : reports.filter((report) => report.status === statusFilter);

  return (
    <div className="p-6 bg-gray-100 min-h-screen">
      <h1 className="text-2xl font-bold text-gray-800 mb-6">Reports</h1>

      <div className="mb-6 flex justify-between items-center">
        <div>
          <h2 className="text-lg font-semibold text-gray-800">Filter by Status</h2>
          <select
            className="mt-2 p-2 border border-gray-300 rounded"
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="All">All</option>
            <option value="Completed">Completed</option>
            <option value="Pending">Pending</option>
          </select>
        </div>


        <button className="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600">
          Download All Reports
        </button>
      </div>


      <div className="overflow-x-auto bg-white shadow rounded-lg">
        <table className="w-full table-auto">
          <thead className="bg-gray-200">
            <tr>
              <th className="py-3 px-4 text-left text-gray-600">Report Title</th>
              <th className="py-3 px-4 text-left text-gray-600">Date</th>
              <th className="py-3 px-4 text-left text-gray-600">Generated By</th>
              <th className="py-3 px-4 text-left text-gray-600">Status</th>
              <th className="py-3 px-4 text-left text-gray-600">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredReports.map((report) => (
              <tr key={report.id} className="border-b">
                <td className="py-3 px-4 text-gray-800">{report.title}</td>
                <td className="py-3 px-4 text-gray-800">{report.date}</td>
                <td className="py-3 px-4 text-gray-800">{report.generatedBy}</td>
                <td
                  className={`py-3 px-4 text-gray-800 ${
                    report.status === "Completed" ? "text-green-500" : "text-red-500"
                  }`}
                >
                  {report.status}
                </td>
                <td className="py-3 px-4">
                  <button
                    className={`py-2 px-4 rounded ${
                      report.status === "Completed"
                        ? "bg-green-500 text-white hover:bg-green-600"
                        : "bg-yellow-500 text-white hover:bg-yellow-600"
                    }`}
                  >
                    {report.actions}
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ReportPage;
